# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_mentor', models.BooleanField(default=False)),
                ('grad_year', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
                ('email_end', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='university_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.University'),
        ),
    ]
