# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_avail',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='student',
            name='rel_interest',
            field=models.CharField(default='new friends', max_length=100),
            preserve_default=False,
        ),
    ]
